server:
  port: 8081

telegram-bot:
  userName: 'https://t.me/firstGroupSupportBot'
  token: '6351549076:AAF7uGio6Aan17f4md_yA4fZmj6HjPTbRfg'

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demo_db
    username: postgres
    password: root777
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
      ddl-auto: create
    show-sql: true